#!/bin/bash



#================= exports
export LOCAL_BIN="${HOME}/.local/bin"
export LOCAL_BASH=$LOCAL_BIN/bash/
export SCALA_HOME=$LOCAL_BIN/scala/default
export DART_HOME=$LOCAL_BIN/dart/default
export NODEJS_HOME=$LOCAL_BIN/nodejs/default
export GRADLE_HOME=$LOCAL_BIN/gradle/default
export MAVEN_HOME=$LOCAL_BIN/maven/default
export GROOVY_HOME=$LOCAL_BIN/groovy/default
export JAVA_HOME=$LOCAL_BIN/jdk/default
export JAVA_21_HOME=$LOCAL_BIN/jdk/21
export CATALINA_HOME=$LOCAL_BIN/tomcat/default
export ANT_HOME=$LOCAL_BIN/ant/default
export DERBY_HOME=$LOCAL_BIN/derby/default
export FLUTTER_HOME=$LOCAL_BIN/flutter/default
export PATH=$PATH:$JAVA_HOME/bin:$GRADLE_HOME/bin:$NODEJS_HOME/bin:$LOCAL_BIN/bash:$MAVEN_HOME/bin:$CATALINA_HOME/bin:$ANT_HOME/bin:$GROOVY_HOME/bin:$SCALA_HOME/bin:$ANT_HOME/bin:$DERBY_HOME/bin:$FLUTTER_HOME/bin

source /etc/bash_completion.d/git-prompt
#================= statics







