#!/usr/bin/bash

#$1 source dir
#$2 type of share [smb/ftp/http]
#check parents access permissions
#why we can't execute as root inside?

if [[ $# -ne 2 ]]; then
	echo 'ERR: Requires 2 args, $1 for dir and $2 for service'
	exit 1
elif [[ ! -d $1 ]]; then
	echo "ERR: Invalid dir path or not exists"
	exit 1
#elif [[ `id -u` -ne 0 ]]; then
	#echo "ERR: This script requires root access, please run again with sudo privileges"
	#exit 1
elif [[ ! -f $LOCAL_BASH/file_utils ]]; then
	echo "ERR: file_utils is required, but was not exists in path: $LOCAL_BASH/file_utils"
	exit 1
fi


source $LOCAL_BASH/file_utils

smb_conf=/etc/samba/smb.conf
ftp_conf=/etc/vsftpd.conf
path_to_share=`resolveRelativePath "$1"`
path_to_share=`echo "$path_to_share" | tr -s '/'`
dir_name=`basename "$path_to_share"`

g=("owner" "group" "others")
IFS="/" read -r -a arr <<< "$path_to_share"
tmp=
for a in "${arr[@]}"; do
	tmp+="$a/"
	pp=`stat -c "%a %n" "$tmp"`
	for i in {0..2}; do 
		if [[ $i -eq 1 ]]; then continue; fi
		octal=${pp:$i:1}
		if [[ "$octal" -ne 7 && "$octal" -ne 5 ]]; then
			echo "WAR: The '${g[i]}' octal permission '$octal' is invalid on the path-hierarchy of: $pp"
			echo "WAR: The '${g[i]}' permission should be either '7' or '5' to gain path-hierarchy access"
			echo -e "[Yes] to continue without changing it\n[No] to abort\n[C] to change permissions on current dir only\n[R] to change permissions on the entire path-hierarchy from ${pp:0:3} to 755"
			while read -e yn; do
			case $yn in
				[Yy]es|[Yy]) break;;
				[Nn]o|[Nn]) 
					echo "LOG: Aborting.."; 
					exit 0
				;;
				[Cc]) chmod 755 "$tmp"; break;;
				[Rr]) chmod -R 755 "$tmp"; break;;
				*) 
					echo "ERR: Unknown command, please try again"
					sleep 1s
					echo "LOG: Are you sure want to continue with above settings [yes/no]?"
				;;
			esac
			done
			
		fi
		
	done
done


case $2 in
	"smb")
		which samba
		if [[ $? -ne 0 ]]; then
			echo "ERR: samba not installed, aborting"
			exit 1
		fi
	
		grep -oE "\[$dir_name\]" $smb_conf
		if [[ $? -eq 0 ]]; then
			echo "ERR: The given path already exists in $smb_conf, aborting.."
			exit 1
		fi

		echo "==================="
		smb_share="[$dir_name]
  comment = Simple Share of $dir_name
  path = $path_to_share
  browsable = yes
  guest ok = yes
  read only = yes" 		
		echo "$smb_share"
		echo "==================="
		echo "LOG: Are you sure want to continue [yes/no]?"
		while read -e yn; do
		case $yn in
			[Yy]es|[Yy]) break;;
			[Nn]o|[Nn]) 
				echo "LOG: Aborting.."; 
				exit 0
			;;			
			*) 
				echo "ERR: Unknown command, please try again"
				sleep 1s
				echo "LOG: Are you sure want to continue with above settings [yes/no]?"
			;;
		esac
		done
		
		
		if [[ ! -f "${smb_conf}_bkp" ]]; then
			echo "LOG: Making backup for $smb_conf --> ${smb_conf}_bkp"
			sudo cp "$smb_conf" "${smb_conf}_bkp"
			if [[ $exitcode -ne 0 ]]; then
				echo "backing-up $ftp_conf failed with exit code: $exitcode"
				exit $exitcode
			fi
		fi
		
		
		tmp_d=/tmp/share_dir
		mkdir -p $tmp_d
		tmp="$tmp_d/`date +%s`.sh"
		echo "#!$BASH" >> $tmp
		echo "echo -e \"$smb_share\" >> $smb_conf" >> $tmp
		echo $tmp
		chmod 777 $tmp
		sudo $tmp
		
		echo "LOG: Restarting services smbd.service and nmbd.service"
		sudo systemctl restart smbd.service nmbd.service
		
		echo "done"
	;;
	
	"ftp")
			
			
		which vsftpd
		if [[ $? -ne 0 ]]; then
			echo "ERR: vsftpd not installed, aborting"
			exit 1
		fi
		
		ftp_share="
allow_writeable_chroot=YES
anon_mkdir_write_enable=YES
anon_other_write_enable=YES
anon_root=__PATH__
anon_upload_enable=YES
anon_world_readable_only=NO
anonymous_enable=YES
connect_from_port_20=YES
dirmessage_enable=YES
hide_ids=YES
listen_ipv6=YES
listen=NO
local_enable=YES
no_anon_password=YES
nopriv_user=ftp
pam_service_name=vsftpd
pasv_max_port=50000
pasv_min_port=40000
rsa_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
rsa_private_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
secure_chroot_dir=/var/run/vsftpd/empty
ssl_enable=NO
use_localtime=YES
write_enable=YES
xferlog_enable=YES		
		"
		
		if [[ ! -f "${ftp_conf}_bkp" ]]; then
			echo "LOG: Making backup for $ftp_conf --> ${fpt_conf}_bkp"
			sudo cp "$ftp_conf" "${ftp_conf}_bkp"
			exitcode=$?
			if [[ $exitcode -ne 0 ]]; then
				echo "backing-up $ftp_conf failed with exit code: $exitcode"
				exit $exitcode
			fi
			
		fi	
		ftp_share="${ftp_share/__PATH__/$path_to_share}"
		
				
		tmp_d=/tmp/share_dir
		mkdir -p $tmp_d
		tmp="$tmp_d/`date +%s`.sh"
		echo "#!$BASH" >> $tmp
		echo "echo -e \"$ftp_share\" > $ftp_conf" >> $tmp
		echo $tmp
		chmod 777 $tmp
		sudo $tmp
		
		
		oct=`stat -c "%a" "$path_to_share"`
		if [[ $oct -ne 777 ]]; then
			echo "$oct $path_to_share"
			echo "It's recomanded to apply read and write permissions to the share dir"
			read -p "You have to do it manually, press enter to continue..."			
		fi
		
		
		sudo systemctl restart vsftpd
	;;
	
	"http")
		echo "unsupported"
		exit 1
	;;
	*) 
	echo "ERR: $2 is unsupported service, aborting"
	exit 1
	;;
esac

    


