#!/bin/bash



function convert(){
	file=$1	
	if [[ -f $file ]]; then
		
		fullName=$(basename -- "$file")
		ext0="${fullName##*.}"
		name0="${fullName%.*}"
		echo $ext0
		echo $name0
		if [[  $ext0 == "ts" ]]; then				
			echo "converting ${file}"	
			ffmpeg -i $file -map 0 -c copy "${name0}.mp4"
		fi
	fi
}


############# loop over arguments
i=1;
j=$#;
while [ $i -le $j ] 
do
		if [[ -d $1 ]]; then
		for file in $1/* ; do
			convert $file
		done
		elif [[ -f $1 ]]; then 	
			convert $1
		fi    
    i=$((i + 1));
    shift 1;
done





